/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wifi;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("Started");

        int port = 2222;

        TCPConnection socket = new TCPConnection(port);

        String input;
        while ((input = socket.read()) != null) {
            System.out.println(input);
            socket.send(input);
        }
    }
}
